### ISSUE TITLE
AttributeError: 'module' object has no attribute 'UiPlugin'

### ISSUE THREAD

**Issue by guillaumemolter** [MoonshineSG/OctoPrint-Mobile#9]
I get the following errors after installation:
```
2016-12-05 22:17:20,789 - octoprint.plugin.core - ERROR - Something went wrong while retrieving package info data for module octoprint_nautilus
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.2.18-py2.7.egg/octoprint/plugin/core.py", line 554, in _find_plugins_from_entry_points
    module_pkginfo = InstalledEntryPoint(entry_point)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.2.18-py2.7.egg/octoprint/plugin/core.py", line 1126, in __init__
    pkginfo.Installed.__init__(self, package, metadata_version=metadata_version)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/pkginfo-1.2.1-py2.7.egg/pkginfo/installed.py", line 15, in __init__
    __import__(package)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_nautilus/__init__.py", line 59, in <module>
    class NautilusPlugin(octoprint.plugin.UiPlugin,
AttributeError: 'module' object has no attribute 'UiPlugin'
2016-12-05 22:17:20,819 - octoprint.plugin.core - ERROR - Error loading plugin nautilus
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.2.18-py2.7.egg/octoprint/plugin/core.py", line 601, in _import_plugin
    instance = imp.load_module(key, f, filename, description)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_nautilus/__init__.py", line 59, in <module>
    class NautilusPlugin(octoprint.plugin.UiPlugin,
AttributeError: 'module' object has no attribute 'UiPlugin'
```
OctoPrint 1.2.18
OctoPi 0.14.0
apt-get update && upgrade done
pip update done

**Comment by MoonshineSG** [comment]
If you read carefully the plugin requirements, you'll notice the min required version for OctoPrint is 1.3.0rc1
